Lab_App/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import ListView, TemplateView
from Lab_App.views import *

app_name = "Lab_App"

urlpatterns = [
    # Home
    path('', lab_home, name='home'),

    # Add article
    url(r'^experiments/(?P<pk>\d+)/articles/create/$', login_required(CreateArticle.as_view()), name='create_article'),

    # Experiment List
    url(r'^experiments/$',
        login_required(
            ListView.as_view(queryset=Experiment.objects.all().order_by('-init_date'),  # Query to get all experiments
                             context_object_name='exp_list_obj',  # variable where is stored
                             template_name='experiment_list.html')), name='experiments'),

    # Experiment details
    url(r'^experiments/(?P<pk>\d+)/$', login_required(ExperimentDetail.as_view()), name='experiment_details'),

    path('autocomplete/', autocomplete, name='autocomplete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', login_required(SignUpView.as_view()), name='signup'),

]

Laboratory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Lab_App.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('api/', include('apiREST.urls'), name='REST_api'),
]

apiREST/urls.py
from django.contrib import admin
from django.urls import path, include
from .api_views import *

urlpatterns = [
    # Login api points
    path('token/', token),
    path('token/refresh/', refresh_token),
    path('token/revoke/', revoke_token),
    path('token/revoke/', revoke_token),

    # Own api points
    path('', mainApi),
    # FOr the detail view and the list view, the same method
    path('experiments/', api_experiments_list),
    path('experiments/<experiments_pk>', api_experiments_list),

]

Lab_App/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.db import models

from phone_field import PhoneField


# Create your models here.
# Models/tables/classes that the DB will have
# After adding one, do
# python manage.py makemigrations webtodo  -- Creates file 001_initial, which will transform python to sql
# python manage.py migrate   --  uses function to transform the python table to sql
# or tools>manage.py


class User(AbstractUser):
    USER_TYPE_CHOICES = [('scientist', 'Scientist'), ('admin', 'Administrator'), ]
    user_type = USER_TYPE_CHOICES


class Administrator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='Administrator_profile')
    name = models.CharField(max_length=50, null=True)
    pass


class Experiment(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    status = models.CharField(max_length=30)
    init_date = models.DateField()

    def __str__(self):
        return str(self.name)


class Scientist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='Scientist_profile')
    name = models.CharField(max_length=50)
    phone_numb = PhoneField(blank=True, help_text='Contact phone number')
    city = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    birth_date = models.DateField(null=True)
    position = models.CharField(max_length=30)
    experiment = models.ForeignKey(Experiment, null=True, on_delete=models.PROTECT, related_name='presentInExperiment')

    def __str__(self):
        return str(self.name)


class Article(models.Model):
    title = models.CharField(max_length=50)
    publish_date = models.DateField()
    body = models.TextField(max_length=500)
    author = models.ForeignKey(Scientist, null=True, on_delete=models.PROTECT)
    experiment = models.ForeignKey(Experiment, null=True, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.title)


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    version = models.FloatField()
    experiment = models.ForeignKey(Experiment, null=True, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.name)

Lab_App/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms import ModelForm
from django import forms

import Lab_App
from Lab_App.models import *


class ArticleForm(ModelForm):

    def __init__(self, *args, **kwargs):
        exPK = kwargs.pop('experimentpk', None)
        experiment = Experiment.objects.filter(pk=exPK).get()
        super(ArticleForm, self).__init__(*args, **kwargs)  # populates the post
        self.fields['author'].queryset = experiment.presentInExperiment.all()

    class Meta:
        model = Article
        exclude = ('user', 'date', 'experiment',)


class SignUpForm(UserCreationForm):

    user_type = forms.CharField(label='Type of account: ', widget=forms.Select(choices=User.USER_TYPE_CHOICES))
    name = forms.CharField()

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.user_type = self.cleaned_data.get('user_type')
        user.save()
        if user.user_type == 'scientist':
            scientist = Scientist.objects.create(user=user)     #Create associated Model
            scientist.name = self.cleaned_data.get('name')
            scientist.save()
        elif user.user_type == 'admin':
            admin = Administrator.objects.create(user=user)     #Create associated Model
            admin.name = self.cleaned_data.get('name')
            admin.save()
        return user

Lab_App/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.urls import reverse
from django.views.generic import DetailView, CreateView

from Lab_App.forms import ArticleForm, SignUpForm
from Lab_App.models import *


# Create your views here.
def experiments_page(r):
    experiments = Experiment.objects.order_by('pk')
    list_experiments = ", ".join([experiment.name for experiment in experiments])
    return HttpResponse(list_experiments)

def autocomplete(request):
    if "term" in request.GET:
        scientistqr = Scientist.objects.filter(name__istartswith=request.GET.get('term'))
        scientist_list = list()
        for scientist in scientistqr:
            scientist_list.append(scientist.name)
        return JsonResponse(scientist_list, safe=False)
    print("bruh")

class ExperimentDetail(DetailView):
    model = Experiment
    template_name = 'experiment_detail.html'

@login_required
def lab_home(request):
    article_list = Article.objects.order_by('-publish_date')
    scientist_list = Scientist.objects.order_by('-name')
    template = loader.get_template('laboratory_home.html')
    context = {
        'article_list': article_list,
        'scientist_list': scientist_list,
    }
    return HttpResponse(template.render(context, request))


class CreateArticle(CreateView):
    model = Article
    template_name = 'form.html'
    form_class = ArticleForm


    def get_form_kwargs(self):
        kwargs = super(CreateArticle, self).get_form_kwargs()
        kwargs['experimentpk'] = self.kwargs['pk']
        return kwargs


    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.experiment = Experiment.objects.get(id=self.kwargs['pk'])
        return super(CreateArticle, self).form_valid(form)


    def get_success_url(self):
        return reverse('Lab_App:experiment_details', kwargs={"pk": self.kwargs['pk']})


class SignUpView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'form.html'

    # In case you want to create specific sign ups / function to pass data to the form
    #
    # def get_context_data(self, **kwargs):
    #     kwargs['user_type'] = 'scientist'
    #     return super().get_context_data(**kwargs)
    #     pass

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('Lab_App:home')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!--<link rel="stylesheet" href="{% static "style/base.css" %}"/>-->
    <title>{% block title %}Aperture Science Enrichment Center{% endblock %}</title>
</head>
<body>
<div id="header">
    {% block header %}
    {% endblock %}
</div>

<div id="sidebar">
    {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
             <li><a href="{% url 'Lab_App:signup' %}"> Create an account</a></li>
            <li><a href="{% url 'Lab_App:experiments' %}"> Experiments </a></li>
            <li><a href="{% url 'rest_framework:logout' %}"> Log out </a></li>
        </ul>{% endblock %}
</div>
<div id="content">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>
<div id="footer">{% block footer %}{% endblock %}</div>
</body>
</html>

templates/experiment_detail.html
{% extends "base.html" %}
{% block content %}
    <h1>
        {{ experiment.name }}
    </h1>
    <h2>Description</h2>
    <p>
        {{ experiment.description }}
    </p>
    <h2>Products Released</h2>
    <ul>
        {% for product in experiment.product_set.all %}
            <li>
                <h3>{{ product.name }}</h3>
                <p>{{ product.description }}</p>
                <p>Version {{ product.version }}</p>
            </li>
        {% endfor %}
    </ul>
    <h2>News/Updates related to this experiment</h2>
    <a href="{% url 'Lab_App:create_article' experiment.id %}"> Create Article</a>
    <ul>
        {% for article in experiment.article_set.all %}
            <li>
                <h3>{{ article.title }}</h3>
                <p>{{ article.body }}</p>
                <p>Publish Date {{ article.publish_date }}</p>
                <p>Author {{ article.author }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}
{% block footer %}
{% endblock %}

templates/experiment_list.html
{% extends "base.html" %}
{% block content %}
    <h1>
        Experiments

    </h1>
    <ul>
        {% for experiment in exp_list_obj %}
            <li><a href="{% url 'Lab_App:experiment_details' experiment.id %}">
                {{ experiment.name }}</a></li>
        {% empty %}
            <li>Sorry, no experiments registered yet.</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/form.html
{% extends "base.html" %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

templates/laboratory_home.html
{% extends "base.html" %}
{% block content %}
    <script>
        $(function () {
            $("#Scientists").autocomplete({
                source: '{% url "Lab_App:autocomplete" %}'
            });
        });
    </script>

  <script>
    $(function() {
      $("#Language").autocomplete({
        source: function(request, response) {
          $.ajax({
            url: "https://translation.googleapis.com/language/translate/v2/languages",
            dataType: "json",
            data: {
              nameStartsWith: request.term,
              limit: 10,
              apikey: "c71fcda3efd3a3e67d4b1878e138afe0"
            },
            success: function(data) {
              console.log(data);
              response($.map(data.data.results, function(item) {
                return {
                  label: item.name,
                  value: item.name
                }
              }));
            }
          });
        },
        minLength: 5,
        select: function(event, ui) {
          if (ui.item) {}
        }
      });
    });
  </script>

    <div class="ui-widget">
        <label for="Scientists">Scientists: </label>
        <input id="Scientists">
    </div>

    <div class="ui-widget">
        <label for="Language">Language: </label>
        <input id="Language">
    </div>

    <h1 align="center">APERTURE SCIENCE</h1>
    <h2>Science Team</h2>
    <table style="width:50%">
        {% for scientist in scientist_list %}
            <td>
                <p>{{ scientist.name }}</p>
            </td>
        {% endfor %}
    </table>
    <h2>News and Articles</h2>
    {% for article in article_list %}
        <br>
        <h3>{{ article.title }}</h3>
        <h4>From: {{ article.experiment }}</h4>
        <p>{{ article.body }}</p>
        <p>Publish Date: {{ article.publish_date }}</p>
        <p>Author: {{ article.author }}</p>
    {% endfor %}

{% endblock %}
{% block footer %}
{% endblock %}